name: snowflake-devops
# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'Snowflake_Learning/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

- name: Debug environment variables
  run: |
    echo "SF_ACCOUNT: ${SF_ACCOUNT:-<empty>}"
    echo "SF_USER: ${SF_USER:+[set]}"
    echo "SF_PASSWORD: ${SF_PASSWORD:+[set]}"
  env:
    SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SF_USER: ${{ secrets.SNOWFLAKE_USER }}
    SF_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SF_USER: ${{ secrets.SNOWFLAKE_USER }}
          SF_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SF_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SF_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          pip install schemachange
          echo "Running schemachange..."
          schemachange -f $GITHUB_WORKSPACE/Snowflake_Learning \
            -a $SF_ACCOUNT \
            -u $SF_USER \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -s $SF_SCHEMA \
            -c $SF_DATABASE.$SF_SCHEMA.CHANGE_HISTORY \
            --create-change-history-table
