name: snowflake-devops-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Snowflake_Learning/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install and Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_SCHEMA: Snowflake_Learning  # You can also make this a secret if needed
        run: |
          echo "Installing schemachange..."
          pip install schemachange

          echo "Running schemachange..."
         schemachange deploy \
        -f $GITHUB_WORKSPACE/Snowflake_Learning \
        -a $SNOWFLAKE_ACCOUNT \
        -u $SNOWFLAKE_USER \
        -r $SNOWFLAKE_ROLE \
        -w $SNOWFLAKE_WAREHOUSE \
        -d $SNOWFLAKE_DATABASE \
        -s $SNOWFLAKE_SCHEMA \
        -c $SNOWFLAKE_DATABASE.$SNOWFLAKE_SCHEMA.CHANGE_HISTORY \
      --create-change-history-table

